### ISSUE TITLE
Why chan *chan interface{} vs just using chan chan interface{}?

### ISSUE THREAD

**Issue by tleyden** [gagliardetto/simpleQueue#1]
[This](https://github.com/gagliardetto/simpleQueue/blob/master/q.go#L14) seems odd:

```
workerPool chan *chan interface{}
```

What's the advantage of using a `*chan` over just using a `chan`, since `chan` is already a reference type?

Feels like it should use this instead:

```
workerPool chan chan interface{}
```

**Comment by gagliardetto** [comment]
You are right.
